<?xml version="1.0" encoding="utf-8"?><Database Name="KTPM" Class="dataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LIAMHEMS;Initial Catalog=KTPM;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="KTPMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TK" Member="TKs">
    <Type Name="TK">
      <Column Name="[User]" Member="User" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Pass" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IsAllow" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ConfirmText" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>